### ISSUE TITLE
V4- Delete player

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#11]
---
name: User story template
about: This template provides a basic structure for user story issues.

---

# User story
As a user , I want to have a delete button on edit modal , so I can remove some players

# Acceptance criteria

- [x] with click on a player ,open edit modal and with delete button remove the player

# Tasks
- Frontend
- [x] add delete button to player modal
- [x] it should  be there just by editing modal and not by new player modal
- [x] axios for delete
- Backend
- [x] add deleteMapping in Controller and its method in service and related unit test and integration test

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified
