### ISSUE TITLE
V5-TournamentList

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#16]
# User story
As a user I want to have a button (Tournaments) in Homepage, so I can see the all of tournaments in TournamentList page.

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [x]  observable Button in Homepage with function to Tournament List page

# Tasks
- Frontend
- [x] create Tournament component and fields for name and location and id and number of player
- [x] create TournamentTable component  to show all of tournaments together with some css
- [x]  create TournamentList component to show TournamentTable and Title 

- Backend
- [x] create Tournament model
- [x] create repository with spring repo
- [x] create service with getAllTournaments method
- [x] create controller with tournaments endpoint with getMapping
- [x] Write unite test for getAllTournaments in Service
- [x] Write Integration test for GetMapping(getAllTournaments)  

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
