### ISSUE TITLE
V6-New Tournament

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#18]
# User story
As a user I want to have a button (New Tournaments) in Tournament List, so I can add New Tournament due a Modal with Name and location and number of Player and see it in Tournament List.

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [x]  observable Button in Tournament List and Modal Pop up with its functions 

# Tasks
- Frontend
- [x] create Tournament Modal and fields for name and location  and number of player
- [x] add post axios to create new Tournament component

- Backend
- [x] add addNewTournament in Tournament Service
- [x] add PostMapping in Controller
- [x]  Write unite test for addNewTournaments in Service
- [x] Write Integration test for GetMapping(addNewTournaments)  

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
