### ISSUE TITLE
V1- Title and Player List

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#2]
# User story
As a user I want to the list of player, so I can see the all of them.

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ]  observable main title  on Top of site and list of players

# Tasks
- Frontend
- [ ] new h element for title some css for it
- [ ] create player component and fields for first name and last name and number with head line
- [ ] create collection component  to show all of players together with some css

- Backend
- [ ] create player model
- [ ] create repo with a list of player
- [ ] create service with getAll method
- [ ] create controller with players endpoint with getMapping

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified
