### ISSUE TITLE
V7,V8- Edit Tournament and Tournament bracket

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#20]
---

# User story
As a User, I want to have Option to edit and save Tournament bracket with new details

# Acceptance criteria

- [x] by click on  Tournament row should open the new page for bracket and in this page should be edit and save and cancel buttons.

# Tasks
- Frontend
- [x] write and design TournamentBracket and create css
- [x] axios put for bracket 
- [x] edit post and get axios for bracket
- [x] navigate from table row to bracket page
- Backend
- [x] putmapping in controller for editing and add methods in service and related Unit test and integration test 
- [x] improve Tournament model for player and matchs

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
