### ISSUE TITLE
V1- Title and Player List

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#3]
# User story
As a user I want to have a button( Player List) in Homepage, so I can see  all of Player in PlayerList Page.

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [x]  observable main title  on Top of site and PlayerList button with function to  list of players

# Tasks
- Frontend
- [x] new h element for title some css for it
- [x] create Player component and fields for first name and last name and id and age
- [x] create playerTable component  to show all of players together with some css
- [ ] create PlayerList component to show PlayerTable and Title 

- Backend
- [x] create player model
- [x] create repository with spring repo
- [x] create service with getAllPlayers method
- [x] create controller with players endpoint with getMapping
- [x] Write unite test for getAllPlayers in Service
- [x] Write Integration test for GetMapping(getAllPlayers)  

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
