### ISSUE TITLE
V2- add edit, new player and new Tournament button

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#3]
# User story
As a user, I want to have the buttons edit , new player and new Tournament, so I can add new player or edit some of them and add new tournament

# Acceptance criteria

- [ ] the button new player , edit and new Tournament should be available and functional

# Tasks
- Frontend
- [ ] add  new player button at the end of player list
- [ ] axios for post
- [ ] add edit button at  right of every player  in playerCard
- [ ] axios for put 
- [ ] add new Tournament button at top of player list in a menu bar
- [ ] the new Tournament should open new site in front end to show a  Tournament diagram
- Backend
- [ ] postmapping in cotnroller for new player button and add method in service and repo
- [ ] putmapping in controller to for edit button and update method in service and repo

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified
