### ISSUE TITLE
V9- Delete-Tournament-Backend

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#33]
# User story
As a User, I want delete tournament option 

# Acceptance criteria

- [x] by postmann can delete a Tournament from DB 

# Tasks
- Backend
- [x] add DeleteMapping in TournamentController and its Integrationtest
- [x] add deletTouranment in TournamentService and its unit test 

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
