### ISSUE TITLE
V10- Security

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#34]
# User story
As a user, I want  limited access to endpointsand ,option to signup and login and logout with hashed password and  csrf , and validation for username and password

# Acceptance criteria

- [x] signup and login button and logout button after login with function

# Tasks
- Frontend
- [x] add Login Page and show it in Home
- [x] add login and me function in App.tsx
- [x] add logout  button in Home if user is logged-in
- Backend
- [x] add Spring security in Pom.xml
- [x] add SecurityConfig and RequestMatchers
- [x] add MongoUser and MongoUserRepositoryand findByUsername to sarch in DB
- [x] add MongoUserDetailsService and loadUserByUsername method
- [x] add Argon2PasswordEncoder in securityConfig
- [x] add MongoUserController and GetMapping for me endpoint to call logged-in user
- [x] add Spring-scurity-test dependency and add csrf to securityConfig
- [x] add sessionManagement and requestMatcher for Tournament EndPoints
- [x] add Postmapping for login endpoint
- [x] add Validation tinto MongoUser and another model classes and and @valid inito PlayerController and TournamentController
 

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified
