### ISSUE TITLE
V11,V12- Logout- Signup

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#35]
# User story
As a user , I want to  have logout and signup button , so I can log in and sign up users

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [x] signup and logout buttons with functions

# Tasks
- Frontend
- [x] add logout function in App.tsx and logout button in Home.tsx 
- [x] add signUp component and signup button in Home.tsx and signup function in App.tsx
- [x] add UserWithoutId  
- Backend
- [x] add logout in security config and requestMatcher for logout endpoint
- [x] add signup endpoint in MongoUserController
- [x] add addNewUser with hashedPassword in MongoUserService and add MongoUserWithoutId record
- [x] add requestMatcher for signup in securityconfig
- [x] add unittest for addNewUser in MongoUserService

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified
