### ISSUE TITLE
V13-Edit Tournament bracket phase 2

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#36]
# User story
As a user, I want to have symmetrical diagram and a ülace for winner, can save and edit match info

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [x] symmetrical diagram with edit and save function

# Tasks
- Frontend
- [x] edit App and TournamentList and Bracket to show bracket separatly for every Tournament
- [x] edit Barcket to show correct diagram and calculate correct number of matches pro round
- [x] add a place for winner
- [x] edit PlayerWithScore to two separate 1 and 2 
- [x] addd MatchModel and adjust it for two PlayerWithScore and add axios Put for Tournament bracket
- [x] create MatchWithoutId, TournamentWithoutIdWithMatch, TournamentWithoutId
- [x] add match to TournamentModel and empty match to axios post in NewTournamentModal
- [x] move allTournamentList from TournamentBracket to App
- [x] add home button into signUp page and add delete button and its function to TournamentBracket
- Backend
- [x] create match record, MatchWithoutId and TournamentWithoutIdWithMatch
- [x] add match to Tournament and add matchWithoutId into TournamentWithoutId
- [x] modify addNewTournament and change TournamentInfo in TournamentService
- [x] modify PutMapping in TournamentController
- [x] modify Unit test and Integration test  beacause of adding match in Tournament

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified
