### ISSUE TITLE
V14- Save-MatchsArray

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#37]
# User story
As a user, I want to save all Info of the matches

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [x] edit and save some matches of tournament

# Tasks
- Frontend
- [x] modify all touranment models  and axios post in NewTournamentModal by adding Array of matches
- [x]  modify axios put in Tournament bracket by adding Array of matches
- Backend
- [x] add List<Match> to Tournament and TournamentWithoutIdWithMatch
- [x]  add List<MatchWithoutId> in TournamentWithoutId
- [x] Modiy addNEwTournament and changeTournamentInfo in Service class
- [x] modify all unit  and integration test with Array of matches

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified
