### ISSUE TITLE
V2- add new player 

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#4]
# User story
As a user, I want to have the buttons  new player , so I can add new player to my player list by a modal Pop up

# Acceptance criteria

- [x] the button new player should be available and functional

# Tasks
- Frontend
- [x] add  new player button at the end of player list
- [x] axios for post
- [x] add new modal component wit save and cancel buttons
- 
- [x] Postmapping in cotnroller for new player button and add method in service and repo and related UnitTests and Integration test

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
