### ISSUE TITLE
V16 user access control

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#41]
# User story
As a user, I want to save players and tournaments seperately for every user

# Acceptance criteria

- [x]  Every user should have different saved data in playerList adn tournamentList

# Tasks
- Frontend
- [x] add admin to all Player and Tournament Models
- [x] edit axios.post and axios.put for player and tournament with admin
- [x] send user from app.tsx to above mentioned points
- Backend
- [x] add admin to all Player and Tournament records
- [x] add function in both repository to find by admin
- [x] edit  get ,put and post methods in service classes for Player and Tournament with admin
- [x] adit GettMApiing in Controller for Player and Tournament
- [x] edit all unit tests for Player and Tournament
- [x] edit all integration tests for Player and TOurnament

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified
