### ISSUE TITLE
V18 Modify Login Signup

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#45]
# User story
As a user, I want to have an icon to display inputted password, two password field to confirm password and an error message for it, an error message if given username to signup is existed

# Acceptance criteria

- [x] icon next to password with its function, two password field in signup page with both error messages

# Tasks
- Frontend
- [x] add icon next to password field in Home.tsx
- [x] edit Home.tsx-return to seperate login and logout
- [x] move login and signup button to top side of Home page
- [x] add second field for passwort  to confirm it and show error message 
- [x] add axios Get request in App to check existence of username during signuup
- [x] display error message in signup component
- Backend
- [x] add a method as doesUsernameExistes in UserService and GetMapping in UserController to checkexistence of username during signup
- [x] update addNewUser to send error message if given username is existed
- [x] add unittests for MongoUserService
- [x] add Integrationtests for all endpoints in MongoUSerController

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
