### ISSUE TITLE
V3- add Edit function

### ISSUE THREAD

**Issue by eliasYazdani** [eliasYazdani/CupWithMe#9]
---
name: User story template
about: This template provides a basic structure for user story issues.

---

# User story
As a User, I want to click on the rows of players, so I can edit them in modal pop up and save changes

# Acceptance criteria

- [x] by click on player should open the pop up to edit and save changes .

# Tasks
- Frontend
- [x] add onclick function to rows of table
- [x] axios for put
- Backend
- [x] putmapping in controller for editing and add methods in service and related Unit test and integration test 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
